# matrix

In [1]:
import numpy as np

## create matrix
zero matrix
all ones matrix
identity matrix: ones on diagnal, and others are zeros.

In [11]:
#convert python list to numpy array
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [13]:
#convert list to matrix
a=np.array([1,2,3,4,5,6])
m=a.reshape(2,3)
print(m)
m=a.reshape(3,2)
print(m)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [7]:
#zero matrix

#np.empty()
a=np.empty([2,4])
print(a)

#np.zeros
shape = [2,4]
a=np.zeros(shape)
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
#zero matrix

#np.ones()
a=np.ones([2,4])
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
#identity matrix
a=np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## transform matrix
transpose

In [14]:
#transpose: reshape()
a=np.array([1,2,3,4,5,6])
m=a.reshape(2,3)
print(m)
m=a.reshape(3,2)
print(m)

#trnaspose: transpose()
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.transpose())

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [18]:
#reverse
a=np.array([[1,2,3],[4,5,6]])
print(a)
reverse= np.array([ i[::-1] for i in a[::-1]])
print(reverse)

[[1 2 3]
 [4 5 6]]
[[6 5 4]
 [3 2 1]]


In [25]:
#turn angle
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

#clock around 90: col to row and reverse
t_90=np.array([i[::-1] for i in a.transpose()])
print(t_90)

#clock around 180:last row to first and reverse
t_180= np.array([ i[::-1] for i in a[::-1]])
print(t_180)

#clock round 270 or anticlock 90:
t_270=a.transpose()[::-1]
print(t_270)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 4 1]
 [8 5 2]
 [9 6 3]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[3 6 9]
 [2 5 8]
 [1 4 7]]
